version: "3.7"

services:
   imgx:
      build:
         context: .
      hostname: imgx
      environment:
         - IMGX_ALLOWED_HOST=*
      volumes:
         - "/home:/home"
         - ".:/var/www"
         - "./tmp:/tmp"
      ports:
         - "80:80"

